# Generated by Django 3.0 on 2021-02-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='availabe',
            new_name='available',
        ),
    ]
