# Generated by Django 3.0 on 2021-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210303_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.FloatField(default=0.0, max_length=6),
        ),
    ]
