# Generated by Django 3.0 on 2021-03-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210319_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=16),
        ),
    ]
