# Generated by Django 3.0 on 2021-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210211_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='SMALL', max_length=10),
        ),
    ]
