# Generated by Django 3.0 on 2021-03-23 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_coupen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupen',
            new_name='Coupon',
        ),
    ]
