# Generated by Django 3.0 on 2021-04-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210409_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
