# Generated by Django 3.0 on 2021-02-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_name',
            field=models.CharField(max_length=50),
        ),
    ]
